import type { DataProvider } from './types';
import {
  saveCard,
  getCards,
  updateCard,
  deleteCard,
  saveBanner,
  getBanner,
  deleteBanner,
  saveFloorPlan,
  putFloorPlanBlob,
  getFloorPlan,
  deleteFloorPlan,
  savePlanMeta,
  getPlanMetaBlob,
  deletePlanMeta,
  savePlanRecord,
  getPlanRecords,
  deletePlanRecord,
  createVendor,
  getVendors,
  updateVendor,
  setVendorBannerBlob,
  removeVendorBannerBlob,
  deleteVendorRecord,
  saveInventoryItem,
  getInventoryItems,
  countInventory,
  updateInventoryItem,
  deleteInventoryItem,
} from '../db';

/** The guest provider — IndexedDB via db.ts, exactly the pre-platform app. */
export const localProvider: DataProvider = {
  kind: 'local',
  saveCard,
  getCards,
  updateCard,
  deleteCard,
  saveBanner,
  getBanner,
  deleteBanner,
  saveFloorPlan,
  putFloorPlanBlob,
  getFloorPlan,
  deleteFloorPlan,
  savePlanMeta,
  getPlanMetaBlob,
  deletePlanMeta,
  savePlanRecord,
  getPlanRecords,
  deletePlanRecord,
  createVendor,
  getVendors,
  updateVendor,
  setVendorBannerBlob,
  removeVendorBannerBlob,
  deleteVendorRecord,
  saveInventoryItem,
  getInventoryItems,
  countInventory,
  updateInventoryItem,
  deleteInventoryItem,
};
